# 應用程式基本設定
app = "hidereplier"
primary_region = "ewr"
swap_size_mb = 256

# 應用程式終止設定
kill_signal = "SIGINT"
kill_timeout = 5

# Docker 映像檔設定
[build]
  image = "dfder/hidereplier:latest"

# 環境變數設定區塊
[env]
  # 在此加入環境變數
  BOT_VERSION="1.0.4"
# 資源限制設定
[[vm]]
  cpu_kind = "shared"    # CPU 類型：shared 或 performance
  cpus = 1               # CPU 核心數
  memory_mb = 256       # 記憶體限制 (MB)

# HTTP 服務設定
[http_service]
  internal_port = 8082   # 容器內部端口
  force_https = true     # 強制使用 HTTPS
  auto_stop_machines  = "stop"     #  Options are "off", "stop", or "suspend"
  auto_start_machines = true     # 改為 true
  min_machines_running = 1       # 最小運行機器數
  processes = ["SpringBootApp"]    # 處理程序名稱

  # 健康檢查設定
  [[http_service.checks]]
    grace_period = "120s"         # 增加寬限期
    interval = "120s"             # 檢查間隔
    method = "GET"              # 檢查方法
    timeout = "60s"             # 增加超時時間
    path = "/actuator/health"   # 健康檢查路徑

  # TLS 和 HTTP 處理設定
  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443                  # HTTPS 端口

  # 並發限制設定
  [http_service.concurrency]
    type = "connections"
    hard_limit = 20            # 最大並發連接數
    soft_limit = 15            # 軟限制並發連接數

