server.port=8082
server.address=0.0.0.0
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE:DiscordBotHistoryDB}
hidereplier.version=${BOT_VERSION:dev}
hidereplier.host-url=${HOST_URL:https://hidereplier.fly.dev/}
hidereplier.dc-webhook=${DC_WEBHOOK_URL}
# actuator limitation.
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
# minimize http requset handler. (default is 200).
server.tomcat.max-threads = 4
